development:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_786_development

test:
  adapter: test

staging:
  adapter: redis
  urll: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_786_staging

production:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_786_production
